# Generated by Django 4.0.1 on 2022-05-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_managers_remove_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'пользователь'), ('moderator', 'moderator'), ('admin', 'admin')], default='Unknown', max_length=10, null=True),
        ),
    ]
