# Generated by Django 4.0.1 on 2022-05-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
