# Generated by Django 4.0.1 on 2022-04-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ad_options_alter_author_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='location',
        ),
        migrations.AddField(
            model_name='author',
            name='location',
            field=models.ManyToManyField(to='ads.Location'),
        ),
    ]
