# Generated by Django 4.0.1 on 2022-04-16 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_remove_author_location_author_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='location',
            new_name='location_id',
        ),
    ]
