# Generated by Django 4.0.1 on 2022-05-10 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
