# Generated by Django 4.0.1 on 2022-04-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_rename_location_author_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.DecimalField(decimal_places=6, max_digits=8, null=True),
        ),
    ]
