version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: skypro_l28
      POSTGRES_PASSWORD: skypro_l28
      POSTGRES_DB: skypro_l28
    restart: always
    ports:
    - "5432:5432"

volumes:
  postgres_data:
